### ISSUE TITLE
Отсутствие галочек верификации.

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile_ovk#1]
На основной инстанции у меня есть галочка:
![image](https://user-images.githubusercontent.com/85897688/216148187-a030a1ec-c00c-490c-babe-736faa5a06ab.png)
В мобильной теме про галочки забыли:
![image](https://user-images.githubusercontent.com/85897688/216148276-7c9988f6-4685-4a9a-8a24-417fe6b6d739.png)

**Comment by veselcraft** [comment]
интересно а зе маккерс зарегался в овк

**Comment by myslivets** [comment]
Добавлено
