### ISSUE TITLE
Не открывается страница с ответами

### ISSUE THREAD

**Issue by mrilyew** [OpenVK/mobile_ovk#15]
Если на неё нажать показывается Server Error

**Comment by mrtag-oss** [comment]
Всё открывается

**Comment by myslivets** [comment]
Не удаётся повторить данный баг :(

**Comment by IgordosDev** [comment]
увы, но баг остался, из-за этого все ещё десктоп версией овк пользуюсь с телефона
Если скажете какие логи или какой полезной инфы я могу принести - сделаю
https://github.com/user-attachments/assets/1659f071-22cd-4afe-abd2-025e9f2e83b6

**Comment by mrilyew** [comment]
> увы, но баг остался, из-за этого все ещё десктоп версией овк пользуюсь с телефона Если скажете какие логи или какой полезной инфы я могу принести - сделаю

У меня тоже 500 на 297 странице уведомлений, переоткрываю значит.

**Comment by mrilyew** [comment]
Я думал, дело в недокопированных шаблонах уведомлений, а оказывается шаблон страницы уведомлений старый и вообще не подгружает уведомления из папки. Скоро фикс будет
