### ISSUE TITLE
Ложный скроллинг по горизонтали

### ISSUE THREAD

**Issue by SigmaTel71** [openvk/mobile_ovk#17]
Якобы есть возможность скроллинга страницы по горизонтали, но и как бы нет.
BlackBerry KEY2, Vivaldi 5.6.2868.36 (Chromium 108).

![Screenshot_20230213-022112.png](https://user-images.githubusercontent.com/17989678/218343497-ce4ffe35-ab35-4a70-a9cb-0969f39c14c9.png)

**Comment by myslivets** [comment]
Исправлено
