### ISSUE TITLE
При нажатии на лайк страница перезагружается

### ISSUE THREAD

**Issue by kilyabin** [OpenVK/mobile_ovk#23]
в шапке все написано

https://github.com/openvk/mobile_ovk/assets/65072190/047c6d05-1c2a-4390-845f-fa57c3c6941a

**Comment by tretdm** [comment]
Ой, кек
![изображение](https://github.com/openvk/mobile_ovk/assets/76806170/f556f96b-14b8-4ed7-a5bd-5fa350ac894c)

**Comment by mrilyew** [comment]
Пофикшено by [190e0ac](https://github.com/OpenVK/mobile_ovk/commit/190e0acf3a6a7aac2c4bb96bbcda06bb9dbfaa4c)
