### ISSUE TITLE
Непереведённые на английский строки

### ISSUE THREAD

**Issue by WerySkok** [openvk/mobile_ovk#5]
Не переведены:
* Меню, а также поле поиска
![изображение](https://user-images.githubusercontent.com/15957616/216147056-ecf3ee9e-99ba-438e-bdb3-76d2b6ca1fec.png)

* Кнопка "Подробнее"/"Скрыть", а также пункт "О себе" на странице пользователя
![изображение](https://user-images.githubusercontent.com/15957616/216147395-c97e8c67-3b9c-4976-b70b-825f706cd653.png)

* Заголовок и кнопка "Нравится" на странице поста
![изображение](https://user-images.githubusercontent.com/15957616/216147686-6d2a7531-b93b-4e90-a89e-937ce0b026af.png)

* Заголовок на странице друзей
![изображение](https://user-images.githubusercontent.com/15957616/216147869-f8c69e84-fa0e-44c5-8790-df3306e1ee00.png)

* Заголовок в разделе фотографий (заголовки на странице альбома тоже не переведены)
![изображение](https://user-images.githubusercontent.com/15957616/216148427-15f6d326-42b0-478b-8936-045e8ba41495.png)
![изображение](https://user-images.githubusercontent.com/15957616/216148473-d46d41ab-2276-4531-8bf7-d3c8f1cf7db7.png)

* Заголовок на странице групп
![изображение](https://user-images.githubusercontent.com/15957616/216148718-fe62c152-a4c4-40ac-a1f6-747fc044acaf.png)

* Непереведённая заглушка на странице поиска
![изображение](https://user-images.githubusercontent.com/15957616/216149014-3c507619-dfbc-4396-83e2-88f175dcab5d.png)

* Поля для паролей и кнопка "Выйти" на странице настроек
![изображение](https://user-images.githubusercontent.com/15957616/216149250-fe3eeffb-568e-4244-bdf6-a07541785cab.png)

* Заголовок и поля на странице редактирования профиля (то же самое и на вкладке контактов)
![изображение](https://user-images.githubusercontent.com/15957616/216156129-777171ff-f92e-4c3b-b8ed-e1bcc1cab4de.png)

* Меню на странице группы
![изображение](https://user-images.githubusercontent.com/15957616/216156704-6ee90025-a6db-4a5d-b410-eb564aba132d.png)

* Вкладка и заглушка поиска на странице сообщений
![изображение](https://user-images.githubusercontent.com/15957616/216157086-ddd011bd-c303-4211-9522-6f2e56221149.png)

* Время захода, заглушка и кнопка "Отправить" на странице переписки
![изображение](https://user-images.githubusercontent.com/15957616/216157302-4c72cc2a-3b24-4a53-adb6-374a35c882c7.png)

**Comment by veselcraft** [comment]
да и вообще тут нахуй всё не переведено тема говно

![image](https://user-images.githubusercontent.com/22993408/216157130-c2f1181a-af1f-4a46-b01a-0533d0db1bf6.png)


рофлю просто скучно
