### ISSUE TITLE
Невозможность прикрепить картинку к посту.

### ISSUE THREAD

**Issue by ZAZiOs** [OpenVK/mobile_ovk#6]
https://user-images.githubusercontent.com/85897688/216160271-e0e0a0e5-c1d2-4be7-8fc0-29c33bdab714.mp4

**Comment by ZAZiOs** [comment]
Я, если что, попытался там потыкать кнопку сначала, а потом попробовал драг н дропом.

**Comment by myslivets** [comment]
Данный функционал сейчас пока попросту нереализован, для него пока подготовлена только кнопка
