### ISSUE TITLE
Не отображается список видеозаписей

### ISSUE THREAD

**Issue by thejenja** [OpenVK/mobile_ovk#8]
![image](https://user-images.githubusercontent.com/65224669/216228945-1404ffb9-ece6-4350-9977-07e152d298de.png)

**Comment by mrilyew** [comment]
Пофикшено by [190e0ac](https://github.com/OpenVK/mobile_ovk/commit/190e0acf3a6a7aac2c4bb96bbcda06bb9dbfaa4c)
