### ISSUE TITLE
Лишние скроллбары в разделах "Помощь" и "Поиск людей"

### ISSUE THREAD

**Issue by thejenja** [OpenVK/mobile_ovk#9]
![image](https://user-images.githubusercontent.com/65224669/216232382-0f9cae75-d62a-4f29-a6bf-f0b095e13948.png)
![image](https://user-images.githubusercontent.com/65224669/216232428-f8d34c4c-9f9e-4999-a413-a60292faa47d.png)

**Comment by myslivets** [comment]
Firefox 109.0 - баг не удалось повторить

**Comment by mrilyew** [comment]
По идее пофикшено by [190e0ac](https://github.com/OpenVK/mobile_ovk/commit/190e0acf3a6a7aac2c4bb96bbcda06bb9dbfaa4c) заменой overflow: scroll на overflow: auto
